import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { ArrowRightIcon, Menu } from "lucide-react";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="top-0 w-full flex px-10 lg:px-24 shadow-sm pb-1">
          <div className="flex items-center justify-between w-full">
            <Image className="w-[50px] drop-shadow-lg" src={'/caneca-sem-fundo.png'} width={150} height={150} alt="logo" />
            <span className="ml-2 font-bold text-xl text-zinc-800 drop-shadow-sm">SpecialMug</span>
            <ul className="hidden gap-5 ml-12 text-zinc-600 lg:flex">
              <li>
                Home
              </li>
              <li>Sobre n&oacute;s</li>
              <li>Sobre o produto</li>
            </ul>
            <div className="ml-auto justify-self-end p-1 bg-[#af3e0d] rounded-full">
              <Menu className="text-white " size={'1.25rem'} />
            </div>
          </div>
        </nav>
        {children}
        <footer className="min-h-[30vh] bg-gradient-to-b from-orange-50 to-orange-100 w-full flex flex-col justify-between">
          <Image className="bg-white rounded-full object-cover w-24 h-24 block mx-auto my-10" src={'/caneca-sem-fundo.png'} width={150} height={150} alt="logo" />
          <span className="text-center block mb-2">Made by lypes.agency</span>
        </footer>
        <SpeedInsights />
      </body>
    </html>
  );
}
